name: build and push code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  git-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: dist/
          destination-github-username: 'TeamPiickle'
          destination-repository-name: 'express-build'
          user-email: dev.kayoung@gmail.com
          target-branch: main
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing develop branch with main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_PR }}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          PULL_REQUEST_TITLE: "sync: $BRANCH_NAME -> main -> develop"
