name: build and push code
on:
  push:
    branches:
      - development
      - sprint/**
  pull_request:
    branches:
      - sprint/4th
jobs:
  git-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: /
          destination-github-username: 'TeamPiickle'
          destination-repository-name: 'express-build'
          user-email: dev.kayoung@gmail.com
          target-branch: ${{ steps.extract_branch.outputs.branch }}
          create-target-branch-if-needed: true
